import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateSeedersMovie1723410168925 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `INSERT INTO "movie" ("title", "poster", "description", "genderId") VALUES 
              ('O castelo animado', 'https://odiariodeumcontadordehistorias.wordpress.com/wp-content/uploads/2017/05/howls-moving-castle.jpeg', 'Uma bruxa lança uma terrível maldição sobre a jovem Sophie transformando-a em uma velha. Desesperada, ela embarca em uma odisseia em busca do mago Howl, um misterioso feiticeiro que pode ajudá-la a reverter o feitiço.', (SELECT id FROM "gender" WHERE "gender" = 'Animação' LIMIT 1)),
              ('O Túmulo dos Vagalumes', 'https://www.papodecinema.com.br/wp-content/uploads/2015/11/20200319-tumulo-dos-vagalumes-papo-de-cinema-cartaz.jpg', 'Os irmão Setsuko e Seita vivem no Japão em meio a Segunda Guerra Mundial. Após a morte da mãe em um bombardeio e a convocação do pai para a Guerra, eles vão morar com alguns parentes. Insatisfeitos, saem da cidade e acabam em um abrigo na floresta.', (SELECT id FROM "gender" WHERE "gender" = 'Animação' LIMIT 1)),
              ('Princesa Mononoke', 'https://i0.wp.com/studioghibli.com.br/wp-content/uploads/2020/04/Princesa-Mononoke-DVD-capa-vers%C3%A1til.jpg?fit=1500%2C2124&ssl=1', 'Um príncipe, em busca de uma cura, luta em uma guerra entre a mata e uma colônia mineira. Nesta aventura ele conhece Mononoke.', (SELECT id FROM "gender" WHERE "gender" = 'Animação' LIMIT 1)),
              ('O Castelo no Céu', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRZGpgfuj7VDVDjhu_hrjJaxtWaHpZ9Sw2nGQ&s', 'Sheeta, uma jovem órfã que possui um colar misterioso se une ao mineiro Pazu para procurar uma lendária cidade flutuante. Mas a dupla é perseguida por gananciosos piratas aéreos.', (SELECT id FROM "gender" WHERE "gender" = 'Animação' LIMIT 1)),
              ('A viagem de Chihiro', 'https://i0.wp.com/studioghibli.com.br/wp-content/uploads/2020/04/A-Viagem-de-Chihiro-DVD.jpg?fit=748%2C1074&ssl=1', 'Chihiro e seus pais estão se mudando para uma cidade diferente. A caminho da nova casa, o pai decide pegar um atalho. Eles se deparam com uma mesa repleta de comida, embora ninguém esteja por perto. Chihiro sente o perigo, mas seus pais começam a comer. Quando anoitece, eles se transformam em porcos. Agora, apenas Chihiro pode salvá-los.', (SELECT id FROM "gender" WHERE "gender" = 'Animação' LIMIT 1)),
              ('O Serviço de Entregas da Kiki', 'https://images.justwatch.com/poster/265232672/s718/o-servico-de-entregas-da-kiki.jpg', 'Por ordem de sua mãe, Kiki parte para um aprendizado de um ano, acompanhada por seu gato preto. A um comando de sua vassoura mágica, ela vai parar na charmosa cidadezinha de Moreoastal. Infelizmente, os hotéis locais não aceitam bruxas e a polícia a flagra fazendo algumas travessuras.', (SELECT id FROM "gender" WHERE "gender" = 'Animação' LIMIT 1)),
              ('Dunkirk', 'https://m.media-amazon.com/images/I/9101ShqfIqL._AC_UF1000,1000_QL80_.jpg', 'Durante a Segunda Guerra Mundial, a Alemanha avança rumo à França e cerca as tropas aliadas nas praias de Dunkirk. Sob cobertura aérea e terrestre das forças britânicas e francesas, as tropas são lentamente evacuadas da praia.', (SELECT id FROM "gender" WHERE "gender" = 'Guerra' LIMIT 1)),
              ('Batman - O Cavaleiro Das Trevas', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTjcuAVaLDIGqSiUzqOKChgR7dVdDdqM9Gl6Q&s', 'Após dois anos desde o surgimento do Batman (Christian Bale), os criminosos de Gotham City têm muito o que temer. Com a ajuda do tenente James Gordon (Gary Oldman) e do promotor público Harvey Dent (Aaron Eckhart), Batman luta contra o crime organizado. Acuados com o combate, os chefes do crime aceitam a proposta feita pelo Coringa', (SELECT id FROM "gender" WHERE "gender" = 'Ação' LIMIT 1)),
              ('Vingadores: Ultimato', 'https://img.elo7.com.br/product/zoom/25E7D5A/big-poster-filme-vingadores-ultimato-lo002-tamanho-90x60-cm-poster-cinema.jpg', 'Os Vingadores unem forças para lutar contra Thanos, após o vilão eliminar metade dos seres vivos da galáxia.', (SELECT id FROM "gender" WHERE "gender" = 'Ação' LIMIT 1)),
              ('Gladiador', 'https://upload.wikimedia.org/wikipedia/pt/4/44/GladiadorPoster.jpg', 'Nos dias finais do reinado de Marcus Aurelius (Richard Harris), o imperador desperta a ira de seu filho Commodus (Joaquin Phoenix) ao tornar pública sua predileção em deixar o trono para Maximus (Russell Crowe), o comandante do exército romano. Sedento pelo poder, Commodus mata seu pai, assume a coroa e ordena a morte de Maximus', (SELECT id FROM "gender" WHERE "gender" = 'Ação' LIMIT 1)),
              ('Uncharted: Fora do Mapa', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR0b-2zKe3Wc7RC0GvON0v2i_G7IBQvyLNF_g&s', 'Nathan Drake e seu parceiro canastrão Victor "Sully" Sullivan embarcam em uma perigosa busca para encontrar o maior tesouro jamais encontrado. Enquanto isso, eles também rastreiam pistas que podem levar ao irmão perdido de Nathan.', (SELECT id FROM "gender" WHERE "gender" = 'Aventura' LIMIT 1)),
              ('John Carter - Entre Dois Mundos', 'https://m.media-amazon.com/images/I/61BbLlXQGIL._AC_UF1000,1000_QL80_.jpg', 'Quando o veterano da Guerra Civil John Carter acorda misteriosamente na superfície de Marte, ele não tem ideia da aventura que o aguarda. Ele acaba se envolvendo em um conflito épico entre os habitantes do planeta e o destino de todos está em suas mãos.', (SELECT id FROM "gender" WHERE "gender" = 'Aventura' LIMIT 1)),
              ('Jurassic Park - O Parque dos DinossaurosJurassic Park ', 'https://upload.wikimedia.org/wikipedia/pt/e/e7/Jurassic_Park_poster.jpg', 'Os paleontólogos Alan Grant, Ellie Sattler e o matemático Ian Malcolm fazem parte de um seleto grupo escolhido para visitar uma ilha habitada por dinossauros criados a partir de DNA pré-histórico. O idealizador do projeto e bilionário John Hammond garante a todos que a instalação é completamente segura. ', (SELECT id FROM "gender" WHERE "gender" = 'Aventura' LIMIT 1)),
              ('Free Guy - Assumindo o Controle', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRCImDIR7GAQ38aua05TiSjROox_JdtBATF4A&s', 'Um caixa de banco preso a uma entediante rotina tem sua vida virada de cabeça para baixo quando descobre que é um personagem em um jogo interativo. Agora ele precisa aceitar sua realidade e lidar com o fato de que é o único que pode salvar o mundo.', (SELECT id FROM "gender" WHERE "gender" = 'Comédia' LIMIT 1)),
              ('Todo Mundo Quase Morto', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ8_DkIEmosBIyr2Htsna4t49QSfOEBX3jXRQ&s', 'Um funcionário de vendas de uma loja de eletrônicos e seu melhor amigo precisam salvar seus amigos e suas famílias de zumbis que tomaram conta de Londres.', (SELECT id FROM "gender" WHERE "gender" = 'Comédia' LIMIT 1)),
              ('O Abutre', 'https://br.web.img3.acsta.net/pictures/16/01/21/18/12/579835.jpg', 'Para enfrentar dificuldades de conseguir um emprego formal, o jovem Louis Bloom (Jake Gyllenhaal) decide entrar no agitado submundo do jornalismo criminal independente de Los Angeles. A fórmula é correr atrás de crimes e acidentes chocantes, registrar tudo e vender a história para veículos interessados.', (SELECT id FROM "gender" WHERE "gender" = 'Drama' LIMIT 1)),
              ('Advogado do Diabo', 'https://br.web.img3.acsta.net/medias/nmedia/18/92/45/32/20200728.jpg', 'Kevin Lomax, advogado de uma pequena cidade da Flórida que nunca perdeu um caso, é contratado por John Milton, dono da maior firma de advocacia de Nova York. No início tudo parece correr bem, mas Mary Ann, a esposa do advogado, começa a testemunhar aparições demoníacas. Kevin está empenhado em defender o cliente e cada vez dá menos atenção a sua mulher', (SELECT id FROM "gender" WHERE "gender" = 'Drama' LIMIT 1)),
              ('Emancipation', 'https://upload.wikimedia.org/wikipedia/pt/5/54/Emancipation_Poster.jpg', 'O escravizado Peter foge de seus captores pelos impiedosos pântanos de Louisiana. Ele se esconde em meio à mata selvagem cheia de animais para despistar capatazes, enfrenta noites frias e animais selvagens em uma tortuosa jornada em direção ao Norte.', (SELECT id FROM "gender" WHERE "gender" = 'Histórico' LIMIT 1)),
              ('Babilônia', 'https://br.web.img3.acsta.net/c_310_420/pictures/22/12/20/19/55/5727666.jpg', 'Decadência, depravação e excessos escandalosos levam à ascensão e queda de vários sonhadores ambiciosos na Hollywood dos anos 1920.', (SELECT id FROM "gender" WHERE "gender" = 'Histórico' LIMIT 1)),
              ('Imaculada', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKjTv7M-dtiRRjKMcQC79x00dYiOEpllnp0A&s', 'Cecilia, uma jovem religiosa, se torna freira em um convento isolado na região rural italiana. Após uma gravidez misteriosa, Cecilia é atormentada por forças perversas, enquanto confronta segredos sombrios e horrores do convento.', (SELECT id FROM "gender" WHERE "gender" = 'Terror' LIMIT 1)),
              ('The Watchers', 'https://m.media-amazon.com/images/M/MV5BZjNlYjg5YzYtMmU4ZC00MzA4LWE5YWYtNTJlOTkyZmQ0YzdkXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_QL75_UX190_CR0,0,190,281_.jpg', 'Uma artista de 28 anos fica presa em uma floresta extensa e intocada no oeste da Irlanda. Procurando abrigo, ela fica presa ao lado de três estranhos que são perseguidos por criaturas misteriosas todas as noites.', (SELECT id FROM "gender" WHERE "gender" = 'Terror' LIMIT 1)),
              ('Wonka', 'https://upload.wikimedia.org/wikipedia/pt/3/31/Charlie_and_the_Chocolate_Factory.jpg', 'O jovem chocolateiro Willy Wonka tenta mudar o mundo com um delicioso pedaço de cada vez.', (SELECT id FROM "gender" WHERE "gender" = 'Musical' LIMIT 1)),
              ('Uma Ideia de Você', 'https://br.web.img3.acsta.net/pictures/24/03/06/17/15/1070935.jpg', 'Solène, uma mãe solteira de 40 anos embarca em um romance inesperado com Hayes Campbell, o vocalista de 24 anos da August Moon, a boy band mais popular do planeta.', (SELECT id FROM "gender" WHERE "gender" = 'Romance' LIMIT 1)),
              ('Interestelar', 'https://br.web.img3.acsta.net/pictures/14/10/31/20/39/476171.jpg', 'As reservas naturais da Terra estão chegando ao fim e um grupo de astronautas recebe a missão de verificar possíveis planetas para receberem a população mundial, possibilitando a continuação da espécie. ', (SELECT id FROM "gender" WHERE "gender" = 'Ficção Científica' LIMIT 1)),
              ('Os Oito Odiados', 'https://br.web.img3.acsta.net/c_310_420/pictures/16/01/07/20/59/207268.jpg', 'Em busca de abrigo para se proteger de uma nevasca, dois caçadores de recompensas, um prisioneiro e um homem que alega ser xerife conhecem quatro estranhos.', (SELECT id FROM "gender" WHERE "gender" = 'Faroeste' LIMIT 1))
              `,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DELETE FROM "movie"`);
  }
}
